/**
 * TypeScript mirror of backend/schemas/lesson_plan_schema.py.
 *
 * Keep these types in sync with LESSON_PLAN_SCHEMA (Pydantic). The backend
 * uses llama-cpp grammar-constrained decoding to force model output into
 * this exact shape, so any drift here means the renderer will silently
 * miss fields.
 */

export type AssessmentStrategy = "Conversation" | "Observation" | "Product" | "Mixed";

export interface KSVMatrix {
  knowledge: string[];
  skills: string[];
  values: string[];
}

export interface LessonComponent {
  duration_minutes: number;
  teacher_actions: string[];
  student_actions: string[];
  talking_points: string[];
}

export interface AssessmentBlock {
  strategy: AssessmentStrategy;
  description: string;
  success_criteria: string[];
}

export interface DifferentiationBlock {
  support: string[];
  extension: string[];
  accommodations: string[];
}

export interface OhpcLessonPlan {
  // Table 1 - header / outcomes
  subject: string;
  grade: string;
  duration: string;
  strand: string;
  essential_learning_outcome: string;
  general_objective: string;
  specific_curriculum_outcomes: string[];
  focus_question?: string | null;
  ksv: KSVMatrix;

  // Table 2 - components of the lesson
  introduction_hook: LessonComponent;
  time_to_teach: LessonComponent;
  time_to_practise: LessonComponent;
  time_to_reflect_and_share: LessonComponent;
  assessment: AssessmentBlock;
  differentiation: DifferentiationBlock;
  subject_integration: string[];
  resources: string[];
}

/**
 * Table 3 - Teacher's Reflections.
 * NOT generated by AI. Stored locally alongside the lesson plan and filled
 * in by the teacher post-lesson. Rendered as editable blank cells.
 */
export interface TeacherReflections {
  learners_engaged: string;
  taught_in_timeslot: string;
  assessment_informed_next: string;
  further_development_needed: string;
  change_for_next_year: string;
  other_reflections: string;
}

export const EMPTY_TEACHER_REFLECTIONS: TeacherReflections = {
  learners_engaged: "",
  taught_in_timeslot: "",
  assessment_informed_next: "",
  further_development_needed: "",
  change_for_next_year: "",
  other_reflections: "",
};

/** Fixed display order + labels for the 8 Components of the Lesson. */
export const LESSON_COMPONENT_SLOTS: ReadonlyArray<{
  key: keyof Pick<
    OhpcLessonPlan,
    | "introduction_hook"
    | "time_to_teach"
    | "time_to_practise"
    | "time_to_reflect_and_share"
  >;
  label: string;
  expectedRange: string;
}> = [
  { key: "introduction_hook", label: "Introduction / Prompter / Hook", expectedRange: "2-5 min" },
  { key: "time_to_teach", label: "Time to Teach", expectedRange: "5-7 min" },
  { key: "time_to_practise", label: "Time to Practise", expectedRange: "15-30 min" },
  { key: "time_to_reflect_and_share", label: "Time to Reflect and Share", expectedRange: "3-5 min" },
];

export const TEACHER_REFLECTION_PROMPTS: ReadonlyArray<{
  key: keyof TeacherReflections;
  label: string;
}> = [
  { key: "learners_engaged", label: "Were the learners engaged?" },
  { key: "taught_in_timeslot", label: "Could the plan be taught in the timeslot?" },
  { key: "assessment_informed_next", label: "Did the assessment provide me with the necessary information to plan (or adjust) the next lesson in this subject?" },
  { key: "further_development_needed", label: "Is further development of this Specific Curriculum Outcome needed (rather than moving on to the next Outcome)?" },
  { key: "change_for_next_year", label: "How would I change the lesson plan for next year?" },
  { key: "other_reflections", label: "Other reflections" },
];
