"""
Pydantic schemas for structured OHPC (OECS) lesson plan output.

Used by llama-cpp-python's grammar-constrained decoding (via json_schema arg
on generate_stream) to guarantee model-agnostic, parseable JSON that maps 1:1
onto the official OHPC Lesson Plan Template 12Sept2025 tables:

  Table 1 - Header / Outcomes (Subject, Grade, Duration, Strand, ELO,
            General Objective, Specific Curriculum Outcomes, K/S/V matrix)
  Table 2 - Components of the Lesson (8 fixed slots)
  Table 3 - Teacher's Reflections  -> NOT generated by AI; rendered as blank
            editable cells in the frontend (post-lesson teacher input).

Notes
-----
- Component slot names are fixed keys. The model cannot invent new sections.
- Every component uses the same LessonComponent shape so the frontend can
  render them uniformly.
- LessonComponent.duration_minutes lets the frontend render the "(X min)"
  label next to each component cell without regexing prose.
- talking_points are optional short teacher-dialogue prompts per component,
  per the annotated OHPC template guidance.
"""
from pydantic import BaseModel, Field
from typing import List, Literal, Optional


# -- K/S/V matrix (Table 1 bottom row) --------------------------------------

class KSVMatrix(BaseModel):
    knowledge: List[str] = Field(..., min_length=1, max_length=6)
    skills: List[str] = Field(..., min_length=1, max_length=6)
    values: List[str] = Field(..., min_length=1, max_length=6)


# -- Generic component block (Table 2 rows 1-4) -----------------------------

class LessonComponent(BaseModel):
    duration_minutes: int = Field(..., ge=1, le=60)
    teacher_actions: List[str] = Field(..., min_length=1, max_length=8)
    student_actions: List[str] = Field(..., min_length=1, max_length=8)
    talking_points: List[str] = Field(default_factory=list, max_length=6)


# -- Assessment (Table 2 row 5) ---------------------------------------------

class AssessmentBlock(BaseModel):
    strategy: Literal["Conversation", "Observation", "Product", "Mixed"]
    description: str = Field(..., min_length=10)
    success_criteria: List[str] = Field(..., min_length=1, max_length=6)


# -- Differentiation (Table 2 row 6) ----------------------------------------

class DifferentiationBlock(BaseModel):
    support: List[str] = Field(..., min_length=1, max_length=6)       # struggling learners
    extension: List[str] = Field(..., min_length=1, max_length=6)     # advanced learners
    accommodations: List[str] = Field(default_factory=list, max_length=6)  # SEN / language


# -- Full OHPC lesson plan output -------------------------------------------

class LessonPlanOutput(BaseModel):
    # Table 1 - header / outcomes
    subject: str
    grade: str
    duration: str  # e.g. "60 minutes"
    strand: str
    essential_learning_outcome: str = Field(..., min_length=10)
    general_objective: str = Field(..., min_length=10)
    specific_curriculum_outcomes: List[str] = Field(..., min_length=1, max_length=6)
    focus_question: Optional[str] = None
    ksv: KSVMatrix

    # Table 2 - components of the lesson (fixed slot names)
    introduction_hook: LessonComponent
    time_to_teach: LessonComponent
    time_to_practise: LessonComponent
    time_to_reflect_and_share: LessonComponent
    assessment: AssessmentBlock
    differentiation: DifferentiationBlock
    subject_integration: List[str] = Field(..., min_length=1, max_length=6)
    resources: List[str] = Field(..., min_length=1, max_length=10)


LESSON_PLAN_SCHEMA = LessonPlanOutput.model_json_schema()
